### PR TITLE
Run gofmt on entire codebase

### PR DESCRIPTION
**Pull request by DavidGamba**

### CODE REVIEW

**Comment by nathanaelle** [comment]
Maybe it's time for me to open an accessibility issue about gofmt.

**Comment by nathanaelle** [comment]
thanks 🙂

**Comment by DavidGamba** [comment]
> Maybe it's time for me to open an accessibility issue about gofmt.

What do you mean?

**Comment by nathanaelle** [comment]
I live with a handicap after a brain injury.
I need "typographic rivers" to help me to visualize the structure of the code.

gofmt is a good tool.
but gofmt produce visually a very comptact code, and that compactness create a painful mess in my brain.

**Comment by DavidGamba** [comment]
I am sorry to hear that, I wouldn't have reformatted the code if I knew it would make it harder for you to work with it. 

On a sidenote, I do prefer "typographic rivers", they are very nice, the reason I use gofmt is because it makes the code from different people consistent. You should definitely bring it up. I know other automated tools do a better job of formatting table like structures.

**Pull request merged**
